version: '3.7'
services:
  ngnix:
    image: ngnix
    build: ./requirements/nginx
    restart: on-failure
    container_name: ngnix
    env_file: .env
    ports:
     - "443:443"
    volumes:
     - wordpress_volume:/var/www/html
    depends_on:
     - wordpress
    networks:
      - my_network
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    container_name: mariadb
    env_file: .env
    ports:
     - "3306:3306"
    volumes:
     - database_volume:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    depends_on:
     - mariadb
     - redis
    build: ./requirements/wordpress
    restart: on-failure
    image: wordpress
    container_name: wordpress
    env_file: .env
    ports:
     - "9000:9000"
    volumes:
     - wordpress_volume:/var/www/html
    networks:
      - my_network
  redis:
    build: ./requirements/bonus/redis
    restart: on-failure
    image: redis
    container_name: redis
    env_file: .env
    ports:
     - "6379:6379"
    networks:
      - my_network
  ftp:
    build: ./requirements/bonus/FTP
    restart: always
    image: ftp
    container_name: ftp
    env_file: .env
    ports:
     - "21:21"
     - "20:20"
     - "40000-40005:40000-40005"
    volumes:
     - wordpress_volume:/var/www/html/wordpress
    networks:
      - my_network
  adminer:
    build: ./requirements/bonus/adminer
    restart: on-failure
    image: adminer
    container_name: adminer
    env_file: .env
    ports:
     - "8080:8080"
    networks:
      - my_network
  cadvisor:
    build: ./requirements/bonus/cadvisor
    restart: on-failure
    image: cadvisor
    container_name: cadvisor
    env_file: .env
    ports:
     - "8081:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
       type: none
       device: /Users/bbrahim/Desktop/data/wordpress_volume
       o: bind
  database_volume:
    driver: local
    driver_opts:
       type: none
       device: /Users/bbrahim/Desktop/data/database_volume
       o: bind