version: '3.7'

networks:
  my_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
       device: /Users/bbrahim/Desktop/data/wordpress_volume
       o: bind
  database_volume:
    driver: local
    driver_opts:
       device: /Users/bbrahim/Desktop/data/database_volume
       o: bind

services:
  ngnix:
    build: ./requirements/nginx
    container_name: ngnix
    restart: always
    depends_on:
     - wordpress
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "443:443"
    volumes:
     - wordpress_volume:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "3306:3306"
    volumes:
     - database_volume:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
     - mariadb
     - redis
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "9000:9000"
    volumes:
     - wordpress_volume:/var/www/html

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: on-failure
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "6379:6379"

  ftp:
    build: ./requirements/bonus/FTP
    container_name: ftp
    restart: always
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "20:20"
     - "21:21"
     - "40000-40005:40000-40005"
    volumes:
     - wordpress_volume:/home/bbrahim/ftp

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: on-failure
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "8080:8080"

  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    restart: on-failure
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "8081:8080"
    volumes:
     - "/:/rootfs:ro"
     - "/var/run:/var/run:rw"
     - "/sys:/sys:ro"
     - "/var/lib/docker/:/var/lib/docker:ro"

  website:
    build: ./requirements/bonus/website
    container_name: website
    restart: on-failure
    env_file:
     - .env
    networks:
     - my_network
    ports:
     - "82:82"