version: '3.7'
services:
  ngnix:
    image: ngnix
    build: ./requirements/nginx
    restart: on-failure
    container_name: ngnix
    env_file: .env
    ports:
     - "443:443"
    volumes:
     - wordpress_volume:/var/www/html
    depends_on:
     - wordpress
    networks:
      - my_network
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    container_name: mariadb
    env_file: .env
    ports:
     - "3306:3306"
    volumes:
     - database_volume:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    depends_on:
     - mariadb
    build: ./requirements/wordpress
    restart: on-failure
    image: wordpress
    container_name: wordpress
    env_file: .env
    ports:
     - "9000:9000"
    volumes:
     - wordpress_volume:/var/www/html
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
       type: none
       device: /Users/bbrahim/Desktop/data/wordpress_volume
       o: bind
  database_volume:
    driver: local
    driver_opts:
       type: none
       device: /Users/bbrahim/Desktop/data/database_volume
       o: bind